name: Tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Authenticate to Keyfactor NuGet feed
        run: dotnet nuget add source https://nuget.pkg.github.com/Keyfactor/index.json -n keyfactor -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore
        run: dotnet restore tests/AkeylessPam.Unit.Tests/AkeylessPam.Unit.Tests.csproj

      - name: Run unit tests
        run: dotnet test tests/AkeylessPam.Unit.Tests/ --no-restore --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage/**/coverage.cobertura.xml

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Authenticate to Keyfactor NuGet feed
        run: dotnet nuget add source https://nuget.pkg.github.com/Keyfactor/index.json -n keyfactor -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore
        run: dotnet restore tests/AkeylessPam.Integration.Tests/AkeylessPam.Integration.Tests.csproj

      - name: Run integration tests
        env:
          AKEYLESS_ACCESS_ID: ${{ secrets.AKEYLESS_ACCESS_ID }}
          AKEYLESS_ACCESS_KEY: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          AKEYLESS_API_URL: ${{ vars.AKEYLESS_API_URL }}
          AKEYLESS_SECRET_STATIC_TEXT: ${{ vars.AKEYLESS_SECRET_STATIC_TEXT }}
          AKEYLESS_SECRET_STATIC_TEXT_2: ${{ vars.AKEYLESS_SECRET_STATIC_TEXT_2 }}
          AKEYLESS_SECRET_STATIC_KV: ${{ vars.AKEYLESS_SECRET_STATIC_KV }}
          AKEYLESS_SECRET_STATIC_JSON: ${{ vars.AKEYLESS_SECRET_STATIC_JSON }}
          AKEYLESS_SECRET_STATIC_JSON_RAW: ${{ vars.AKEYLESS_SECRET_STATIC_JSON_RAW }}
        run: dotnet test tests/AkeylessPam.Integration.Tests/ --no-restore
